== Data management 

[NOTE.objectives]
In this module, you will review the main concepts, related tools and best practices for data management, particularly, data cleaning and standardization.

=== Principles of data management
[NOTE.presentation]
In this video (09:49), you will review an important set of principles necessary to improve data through the processes of data cleaning.
If you are unable to watch the embedded video, you can link:../videos/Data_Management.mp4[download^,opts=download] it locally. (MP4 - 16.6 MB)

video::4ijm1cJeVHE[youtube,height=432,width=768,align=center]

=== Data management tools
[NOTE.presentation]
In this video (06:42), you will learn about a variety of tools that you can use to improve the quality of your data.
If you are unable to watch the embedded video, you can link:../videos/Data_Management_Tools.mp4[download,opts=download] it locally. (MP4 - 10.3 MB)

video::Ru3vWiYU3gw[youtube,height=432,width=768,align=center]

=== OpenRefine
[NOTE.presentation]
In this video (03:27), you will learn about https://openrefine.org/[OpenRefine^]. You can use OpenRefine to standardize and improve the quality of your data.
If you are unable to watch the embedded video, you can link:../videos/Data_Management_OpenRefine.mp4[download,opts=download] it locally. (MP4 - 3.8 MB)

video::_YFw_bfwc3Y[youtube,height=432,width=768,align=center]

=== Data journey step 7

[NOTE.activity]
In this activity, you will ...