== Data capture

[NOTE.objectives]
In this module, you will learn the types of primary biodiversity data and how to best share that information within GBIF. 
You will also review principles of data quality in the context of data capture and will learn about data quality and coherence (especially on subjects such as georeferencing, dates, names and taxa cross-checking).

=== Data origins and types

[NOTE.presentation]
In this video (10:45), you will review https://www.gbif.org/dataset-classes[primary biodiversity data^] that can be shared within GBIF. 
If you are unable to watch the embedded video, you can link:../videos/data_origins_types.mp4[download^,opts=download] it locally. (MP4 - 19 MB)

[.responsive-video]
video::wKeOveydjsw[youtube]

=== Data capture, processing and quality
[NOTE.presentation]
In this video (09:11), you will explore the principles of data quality applied to data capture, specifically when capturing data from collection labels, fieldwork notebooks, spreadsheets, etc.
If you are unable to watch the embedded video, you can link:../videos/Data_capture_processing_quality.mp4[download^,opts=download] it locally. (MP4 - 19 MB)

[.responsive-video]
video::QkDJIkmwBMA[youtube]

=== iNaturalist
// [NOTE.presentation]
// In this presentation, you will review ... 
// If you are unable to view the embedded slideshow, you can download it locally. (MP4 - ??.? MB)

[NOTE.field]
In this activity, you will venture into the field for first-person data capture.

ifdef::backend-pdf[]
The presentation can be viewed in the online version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
++++
<div class="responsive-slides responsive-slides-4-3">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTII4tP-7I40yo-wRIStynV1gOaS9HEu1j4j5tH5xZsnzUqOjXqgF5Pd6AXJ0UZqMH8KeY4-GWvrE4T/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++
endif::backend-pdf[]

=== Data journey step 6

[NOTE.activity]
Complete step 6, task 12.