== Data publishing

[NOTE.objectives]
In this module, you will learn about data publishing concepts, including the IPT, cores and extensions, and the importance of licenses, metadata, mandatory fields and hosting of datasets.

=== Data publishing concepts
[NOTE.presentation]
In this video (11:45), you will learn about data publishing concepts and will receive an introduction to the Integrated Publishing Toolkit (https://www.gbif.org/ipt[IPT^]).
If you are unable to watch the embedded video, you can link:../videos/Data_publishing_concepts.mp4[download^,opts=download] it locally. (MP4 - 20 MB)

video::b9O0d9ukjSQ[youtube,height=432,width=768,align=center]

=== IPT overview
[NOTE.presentation]
In this video (06:56), you will receive an overview of the IPT data publishing interface.
If you are unable to watch the embedded video, you can link:../videos/Data_publishing_IPT.mp4[download^,opts=download] it locally. (MP4 - 8.7 MB)

video::gHXsaN_JWeI[youtube,height=432,width=768,align=center]

==== Training IPT installations

If you have not already been provided a login, please contact training@gbif.org and you will be provided with a login and password on the course IPT.

https://training-ipt-a.gbif.org/[^]

https://training-ipt-b.gbif.org/[^]

https://training-ipt-c.gbif.org/[^]

=== IPT demonstration
[NOTE.presentation]
In this video (24:16), you will learn how to publish an occurrence dataset using an IPT.
If you are unable to watch the embedded video, you can link:../videos/IPT_demo.mp4[download^,opts=download] it locally. (MP4 - 52.6 MB)

video::eDH9IoTrMVE[youtube,height=432,width=768,align=center]

=== Data journey step 8

[NOTE.activity]
In this activity, you will ...

=== Data journey step 9

[NOTE.activity]
In this activity, you will ...

=== Data publishing benefits

[NOTE.presentation]
In this presentation, you will review ... 
If you are unable to view the embeded slideshow, you can download it locally. (MP4 - ??.? MB)

