== Data publishing

[NOTE.objectives]
In this module, you will learn about data publishing concepts, including the IPT, cores and extensions, and the importance of licenses, metadata, mandatory fields and hosting of datasets.

=== Data publishing concepts
[NOTE.presentation]
In this video (11:45), you will learn about data publishing concepts and will receive an introduction to the Integrated Publishing Toolkit (https://www.gbif.org/ipt[IPT^]).
If you are unable to watch the embedded video, you can link:../videos/Data_publishing_concepts.mp4[download^,opts=download] it locally. (MP4 - 20 MB)

[.responsive-video]
video::b9O0d9ukjSQ[youtube]

=== IPT overview
[NOTE.presentation]
In this video (06:56), you will receive an overview of the IPT data publishing interface.
If you are unable to watch the embedded video, you can link:../videos/Data_publishing_IPT.mp4[download^,opts=download] it locally. (MP4 - 8.7 MB)

[.responsive-video]
video::gHXsaN_JWeI[youtube]

==== Training IPT installations

If you have not already been provided a login, please contact training@gbif.org and you will be provided with a login and password on the course IPT.

// https://training-ipt-a.gbif.org/[^]

https://training-ipt-b.gbif.org/[^]

// https://training-ipt-c.gbif.org/[^]

=== IPT demonstration
[NOTE.presentation]
In this video (24:16), you will learn how to publish an occurrence dataset using an IPT.
If you are unable to watch the embedded video, you can link:../videos/IPT_demo.mp4[download^,opts=download] it locally. (MP4 - 52.6 MB)

[.responsive-video]
video::eDH9IoTrMVE[youtube]

=== Data journey step 8

[NOTE.activity]
Complete step 8, task 16.

=== Data journey step 9

[NOTE.activity]
Complete step 9, task 17.

=== Data publishing benefits

// [NOTE.presentation]
// In this presentation, you will review ... 
// If you are unable to view the embedded slideshow, you can download it locally. (MP4 - ??.? MB)

==== Benefits

ifdef::backend-pdf[]
The presentation can be viewed in the online version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTiAs2VGESe5nLRACVYBuPtTBL-3P2ibCKUO0R-3BAmIqPIORLCGvvvrAyavrcpYg/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++
endif::backend-pdf[]

==== Scholarly regcognition

ifdef::backend-pdf[]
The presentation can be viewed in the online version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vShQXbzL3zMx7Ev29dcAETy7__rs4QKdllbteedhifI5lM-BR3f4Lm68pXHO6p7mhO3j2qedOVXvOnj/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++
endif::backend-pdf[]
