== Files for download

All files for the course may be downloaded from this page. 
Or if you prefer, all files are linked individually throughout the course as they occur in the curriculum. 
The video files are embedded throughout the course, as well, and play from YouTube. Subtitles are available when playing from YouTube for most videos. 
If you have difficulty accessing the embedded videos, please download the mp4 files to play them locally on your computer.

=== Videos
The videos are narrated in English. Subtitles are not available for the downloaded videos.

link:../videos/Foundations1.zip[Foundations1.zip,opts=download] (73.7 MB)

link:../videos/Foundations2.zip[Foundations2.zip,opts=download] (90.2 MB)

link:../videos/Capture.zip[Capture.zip,opts=download] (63.1 MB)

link:../videos/Management.zip[Management.zip,opts=download] (30.2 MB)

link:../videos/Publishing.zip[Publishing.zip,opts=download] (77.9 MB)

=== Exercise data
Data journey step 4: link:../exercise-data/sequences.zip[sequences.zip file,opts=download] (ZIP 5 KB)

Data journey step 6:

. https://github.com/gbif/ipt/wiki/gbif-ipt-docs/downloads/occurrence_ipt_template_v2.xlsx[Excel template^]
. link:../exercise-data/Vicia.zip[Vicia.zip file,opts=download] (ZIP 51 MB)
