== Introduction 

// [NOTE.objectives]
// This module includes ...

=== Biodiversity of Bulgaria

ifdef::backend-pdf[]
The presentation can be viewed in the online version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vThmqJ446bEuNToKHKRTGoa3Me9j7PPiD2cpSo_EpE1tITjnJHvqRoLw86Oj6_4hw/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++
endif::backend-pdf[]

=== Barcoding, data and biodiversity

// [NOTE.presentation]
// In this presentation, you will review ... used in this course. 
// If you are unable to view the embedded slideshow, you can download it locally. (MP4 - ??.? MB)

ifdef::backend-pdf[]
The presentation can be viewed in the online version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTUi3wtExHZdtkIgugsAoUIPHgy3X8zA_LQvAyKRrk7fcU4N_GR5bzi6eKKJ-LbSA/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++
endif::backend-pdf[]

=== GBIF for science and policy

// [NOTE.presentation]
// In this presentation, you will review ... used in this course. 
// If you are unable to view the embedded slideshow, you can download it locally. (MP4 - ??.? MB)

ifdef::backend-pdf[]
The presentation can be viewed in the online version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQgUXOcYxkKPYH5NN6WRXJwWPWmv5b2mE2PEkXJIRb4MtcmfC8LMZtRvVj6Sr56DA/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++
endif::backend-pdf[]
