https://docs.gbif.org/documentation-guidelines/[image:https://docs.gbif.org/documentation-guidelines/gbif-document-shield.svg[GBIF Document]]
// DOI badge: If you have a DOI, remove the comment ("// ") from the line below, change "10.EXAMPLE/EXAMPLE" to the DOI in all three places, and remove this line.
// https://doi.org/10.EXAMPLE/EXAMPLE[image:https://zenodo.org/badge/DOI/10.EXAMPLE/EXAMPLE.svg[doi:10.EXAMPLE/EXAMPLE]]
// License badge
https://creativecommons.org/licenses/by-sa/4.0/[image:https://img.shields.io/badge/License-CC%20BY%2D-SA%204.0-lightgrey.svg[CC BY-SA 4.0]]
// Build status badge: In the text below, please update "course-template" to "course-your-course-name", and remove this line.
https://builds.gbif.org/job/course-template/lastBuild/console[image:https://builds.gbif.org/job/course-template/badge/icon[Build status]]

= Accelerating biodiversity research through DNA barcodes, collection and observation data

This course is a collaboration between the https://diku.no/[Diku-funded^] University of Oslo project BioDATA, the BMBF-funded project Caucasus Barcode of Life (https://ggbc.eu/[CaBOL^]), and https://www.gbif.org/[GBIF^] - Global Biodiversity Information Facility.

_This is information *about* this course's source code.  It is not part of the document._

This course is available as HTML and PDF at https://docs.gbif-uat.org/course-dna-barcoding[Accelerating biodiversity research through DNA barcodes, collection and observation data].

This course is built using AsciiDoc, for guidance on how to make changes or suggestions see the https://docs.gbif.org/documentation-guidelines/[GBIF Documentation Guidelines].
