== Species identification

[NOTE.objectives]
This module includes ...

=== Why do we need to identify species

[NOTE.presentation]
In this presentation, you will review ... used in this course. 
If you are unable to view the embedded slideshow, you can download it locally. (MP4 - ??.? MB)

ifdef::backend-pdf[]
The presentation can be viewed in the online version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
[.center]
++++
<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTWA6W2GZ0DAcerKTPBhUZjCKIVO6giMDENRNF125ZZzD6lCQa5ObEGDexRDCxk7w/embed?start=false&loop=false" frameborder="0" width="768" height="432" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
++++
endif::backend-pdf[]

==== Data journey step 2

[NOTE.activity]
In this activity you will, ...

==== Data journey step 3

[NOTE.activity]
In this activity you will, ...

=== Species identification and delimitation with DNA 

[NOTE.presentation]
In this presentation, you will review ... used in this course. 
If you are unable to view the embedded slideshow, you can download it locally. (MP4 - ??.? MB)

ifdef::backend-pdf[]
The presentation can be viewed in the online version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
[.center]
++++
<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vS2juc-zyGzLnTqhLB6aRE-PRsv6VL0aycJBPVwg3KMVIK7pEscnmhybH4v0Izk0g/embed?start=false&loop=false" frameborder="0" width="768" height="432" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
++++
endif::backend-pdf[]
