== Species identification

// [NOTE.objectives]
// This module includes ...

=== Why do we need to identify species

// [NOTE.presentation]
// In this presentation, you will review ... used in this course. 
// If you are unable to view the embedded slideshow, you can download it locally. (MP4 - ??.? MB)

ifdef::backend-pdf[]
The presentation can be viewed in the online version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTWA6W2GZ0DAcerKTPBhUZjCKIVO6giMDENRNF125ZZzD6lCQa5ObEGDexRDCxk7w/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++
endif::backend-pdf[]

==== Data journey step 2

[NOTE.activity]
Complete step 2, tasks 4-6

==== Data journey step 3

[NOTE.activity]
Complete step 3, tasks 7-9

=== Species identification and delimitation with DNA 

// [NOTE.presentation]
// In this presentation, you will review ... used in this course. 
// If you are unable to view the embedded slideshow, you can download it locally. (MP4 - ??.? MB)

ifdef::backend-pdf[]
The presentation can be viewed in the online version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQOQO0jmRRIJPOo76ZzIuos2QQdS6gttWF6fTrjXn7D9dA3UuJhYb6jg0LwsAwS_g/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++
endif::backend-pdf[]
