== Species identification

// [NOTE.objectives]
// This module includes ...

=== Why do we need to identify species

// [NOTE.presentation]
// In this presentation, you will review ... used in this course. 
// If you are unable to view the embedded slideshow, you can download it locally. (MP4 - ??.? MB)

ifdef::backend-pdf[]
The presentation can be viewed in the online version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vRQZLI8VzhRrb87G4oFIQ6KjWQFITx3YI65TVZ8_sf2p6mZ1B5fkuRIZA2XlZsrwA/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++
endif::backend-pdf[]

==== Data journey step 2

[NOTE.activity]
Complete step 2, tasks 4-6

==== Data journey step 3

[NOTE.activity]
Complete step 3, tasks 7-9

=== Species identification and delimitation with DNA 

// [NOTE.presentation]
// In this presentation, you will review ... used in this course. 
// If you are unable to view the embedded slideshow, you can download it locally. (MP4 - ??.? MB)

ifdef::backend-pdf[]
The presentation can be viewed in the online version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
++++
<div class="responsive-slides">
  <iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSeKK5P0vYqNSkphBON0gVfAZqdGbVtTEI09TVPqfoIhSFNNSguGXGnf0txp0mvkA/embed?start=false&loop=false" frameborder="0" allowfullscreen="true"></iframe>
</div>
++++
endif::backend-pdf[]
